elastic:
  conn: "http://localhost:9200"
  username: "admin"
  password: "password"
mongo:
  conn: "mongodb://root:password@localhost:27017/"
redis:
  host: localhost
  port: 63791
  password: passwrd
http:
  port: 8085
  read_timeout_ms: 200
  write_timeout_ms: 200
  idle_timeout_ms: 30000
  max_header_kb: 500